[profile.default]
solc_version = "0.8.29"
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]
fs_permissions = [
  { access = "read", path = "chainlink-functions/source.js" }
]
